### ISSUE TITLE
extending it to python?

### ISSUE THREAD

**Issue by ChonghaoSima** [RestlessTail/ggGenshin#1]
Great work! Are you planning to extend it to a python package as the community there is much larger?

**Comment by RestlessTail** [comment]
I'm pleased to extend the package, but I know little about plotting with Python. I've only heard of Matplotlib. Should I extend ggGenshin to Matplotlib?

**Comment by ChonghaoSima** [comment]
That would be great if possible!

Best
Chonghao Sima
________________________________

**Comment by RestlessTail** [comment]
I created a new branch and managed to transplant the package to Matplotlib. I tested it on Windows and Ubuntu and it works well on my computer, but I know little about plotting with Matplotlib before and the code may not be the best implementation.
